In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [3]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 2]], dtype=int32)

In [4]:
arr2

array([[1, 2, 1],
       [2, 2, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
arr1.flatten()  # Return a copy of the array collapsed into one dimension original arr1 remains same

array([1, 2, 2, 1, 2, 2, 1, 2, 2], dtype=int32)

In [7]:
# Expand Dimesion
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [8]:
arr.ndim

1

In [ ]:
np.expand_dims(arr, axis = 0)   # Expand dimesion by one along axis 0(Row wise )

array([[1, 2, 3, 4]])

In [ ]:
np.expand_dims(arr, axis = 1)   # Expand dimesion by one along axis 1(column wise)

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
np.squeeze(arr)  # Decrease Dimension by 1

array([1, 2, 3, 4])

In [ ]:
np.repeat(arr, 3)   # Repeats the array 

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [17]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 2]], dtype=int32)

In [18]:
np.repeat(arr1, 2, axis = 1)

array([[1, 1, 2, 2, 2, 2],
       [1, 1, 2, 2, 2, 2],
       [1, 1, 2, 2, 2, 2]], dtype=int32)

In [23]:
np.roll(arr1, -2, axis = 1)  # Rotates the array

array([[2, 1, 2],
       [2, 1, 2],
       [2, 1, 2]], dtype=int32)

In [24]:
# Operations on numpy string array

a = np.array(["aashish", "singh"])

In [25]:
a

array(['aashish', 'singh'], dtype='<U7')

In [26]:
np.char.capitalize(a)

array(['Aashish', 'Singh'], dtype='<U7')

### Mathematical Functions

In [28]:
arr2

array([[1, 2, 1],
       [2, 2, 1],
       [1, 1, 1]], dtype=int32)

In [29]:
np.sin(arr2)

array([[0.84147098, 0.90929743, 0.84147098],
       [0.90929743, 0.90929743, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098]])

In [30]:
np.cos(arr2)

array([[ 0.54030231, -0.41614684,  0.54030231],
       [-0.41614684, -0.41614684,  0.54030231],
       [ 0.54030231,  0.54030231,  0.54030231]])

In [31]:
np.mod(arr1,arr2)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 0, 0]], dtype=int32)

### Sort Search

In [33]:
b = np.array([8,1,9,2,7])
b

array([8, 1, 9, 2, 7])

In [34]:
np.sort(b)

array([1, 2, 7, 8, 9])

In [35]:
c = np.array([6,4,1,2,9,8,6,2])
np.sort(c)

array([1, 2, 2, 4, 6, 6, 8, 9])

In [36]:
np.searchsorted(c, 5)  # Finds Indices where elements should be inserted to maintain order.

np.int64(4)

In [37]:
d = np.array([0,5,3,1,1,3,4,0,4,0,0,8])
np.count_nonzero(d)

8

In [ ]:
d.byteswap()   # Gives byte representation of all elements in d

array([                 0, 360287970189639680, 216172782113783808,
        72057594037927936,  72057594037927936, 216172782113783808,
       288230376151711744,                  0, 288230376151711744,
                        0,                  0, 576460752303423488])

In [39]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 2]], dtype=int32)

In [40]:
arr2

array([[1, 2, 1],
       [2, 2, 1],
       [1, 1, 1]], dtype=int32)

In [43]:
np.linalg.det(arr2)  # Gets us the determinant of any matrix

np.float64(-1.0)

In [47]:
np.linalg.inv(arr2)

array([[-1.,  1.,  0.],
       [ 1.,  0., -1.],
       [ 0., -1.,  2.]])