In [2]:
import numpy as np
a = np.zeros(5)  #  Return a new array of given shape and type, filled with zeros
a

array([0., 0., 0., 0., 0.])

In [7]:
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,4))  # Only np.zeros and np.ones exists none others

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
arr = np.zeros((1,2,3))
arr

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
arr.ndim

3

In [12]:
arr.shape

(1, 2, 3)

In [ ]:
arr + 5

array([[[5., 5., 5.],
        [5., 5., 5.]]])

In [15]:
np.eye(3)  # Will give a matrix where all diagonal elements are 1 and all others are zero(Identity Matrix)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
np.empty((2,4)) # Will return matrix of give shape and type with random entries

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Some Extra Functions
import random
random.choice((1,2,3,4,5))   # Here random number is generated between 1 and 5

2

In [ ]:
random.random()   # Here random number is generated between 0(included) and 1(excluded)

0.1931207387600633

In [ ]:
lis = [1,2,3,4,5]
random.shuffle(lis)  # Will shuffle list values
lis

[2, 1, 5, 3, 4]

#### Random Numbers Related to numpy

In [40]:
np.random.random_sample((4,))

array([0.22290985, 0.15156491, 0.78748899, 0.53420338])

In [41]:
np.random.rand(2)

array([0.03186462, 0.65339272])

In [42]:
np.random.randn(1,4)

array([[-0.23294477, -0.26728443, -0.11517075,  1.37079304]])

In [ ]:
arr = np.random.randint(1,6, size = (3,4))  # Generate matrix of 2x4 with random intergers between 1 and 6
arr

array([[4, 2, 2, 5],
       [1, 5, 3, 1],
       [1, 4, 1, 3]], dtype=int32)

In [52]:
arr.size

12

#### Reshaping the Array

In [55]:
arr1 = arr.reshape(2,6)

In [ ]:
arr1.size   # Array size will not change, while reshaping size should always be same

12

In [57]:
# Incase when we don't know how we should reshape(suppose row or column count is not given)
arr.reshape(3,-1)

array([[4, 2, 2, 5],
       [1, 5, 3, 1],
       [1, 4, 1, 3]], dtype=int32)

In [58]:
arr.reshape(-1,2)

array([[4, 2],
       [2, 5],
       [1, 5],
       [3, 1],
       [1, 4],
       [1, 3]], dtype=int32)

In [ ]:
arr.reshape(3,2,2)  # No of matrix to divide into, no or rows, no of cols

array([[[4, 2],
        [2, 5]],

       [[1, 5],
        [3, 1]],

       [[1, 4],
        [1, 3]]], dtype=int32)

### Conditions on Array

In [63]:
arr1 = np.random.randint(1,10, (5,6))
arr1

array([[9, 1, 6, 8, 5, 3],
       [8, 7, 1, 6, 8, 7],
       [1, 2, 6, 5, 6, 8],
       [5, 2, 8, 3, 2, 3],
       [9, 4, 9, 1, 8, 1]], dtype=int32)

In [64]:
arr1 > 3

array([[ True, False,  True,  True,  True, False],
       [ True,  True, False,  True,  True,  True],
       [False, False,  True,  True,  True,  True],
       [ True, False,  True, False, False, False],
       [ True,  True,  True, False,  True, False]])

In [65]:
arr1[arr1 > 3]

array([9, 6, 8, 5, 8, 7, 6, 8, 7, 6, 5, 6, 8, 5, 8, 9, 4, 9, 8],
      dtype=int32)

In [66]:
arr1[2]

array([1, 2, 6, 5, 6, 8], dtype=int32)

In [67]:
arr1[0:2, [0,2]]  # 0th row to 2nd row and 0th and 2nd coln

array([[9, 6],
       [8, 1]], dtype=int32)

In [83]:
arr1 = np.random.randint(1,5, (3,4))
arr2 = np.random.randint(1,8, (4,2))

In [84]:
arr1

array([[2, 2, 3, 1],
       [3, 4, 3, 1],
       [3, 1, 4, 1]], dtype=int32)

In [85]:
arr2

array([[1, 1],
       [3, 2],
       [2, 3],
       [5, 1]], dtype=int32)

In [86]:
# Matrix Multiplication >> Different from index wise multiplication
arr1 @ arr2   # 1st way to write matrix multiplication

array([[19, 16],
       [26, 21],
       [19, 18]], dtype=int32)

In [87]:
np.dot(arr1,arr2)   # 2nd way to write matrix multiplication

array([[19, 16],
       [26, 21],
       [19, 18]], dtype=int32)

In [ ]:
arr1/0  # Gives inf in numpy but in python it will throw error

C:\Users\Aashish Singh\AppData\Local\Temp\ipykernel_15428\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [89]:
# Broadcasting
arr = np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [91]:
arr + 5  # This is broadcasting

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [92]:
arr - 5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [93]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
a = np.array([1,2,3,4])   

In [99]:
a.ndim

1

In [100]:
a

array([1, 2, 3, 4])

In [ ]:
arr + a   # Values of a will be added in arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]])

### Transpose

In [106]:
b = np.array([[1,2,3,4]])
b

array([[1, 2, 3, 4]])

In [107]:
b.T

array([[1],
       [2],
       [3],
       [4]])

In [109]:
arr1

array([[2, 2, 3, 1],
       [3, 4, 3, 1],
       [3, 1, 4, 1]], dtype=int32)

In [108]:
arr1.T

array([[2, 3, 3],
       [2, 4, 1],
       [3, 3, 4],
       [1, 1, 1]], dtype=int32)

In [110]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.73205081, 1.        ],
       [1.73205081, 2.        , 1.73205081, 1.        ],
       [1.73205081, 1.        , 2.        , 1.        ]])

In [111]:
np.log10

<ufunc 'log10'>

In [113]:
np.exp(arr1)

array([[ 7.3890561 ,  7.3890561 , 20.08553692,  2.71828183],
       [20.08553692, 54.59815003, 20.08553692,  2.71828183],
       [20.08553692,  2.71828183, 54.59815003,  2.71828183]])

In [115]:
np.min(arr)

np.float64(0.0)